import fs/IFsClient.idl
import io/IRow.idl
import io/IRowReader.idl
import io/IRowWriter.idl
import operations/IOperation.idl
import operations/Operations.idl

package jmr
{
    interface IClient : fs.IFsClient
    {
        string GetVersionString();

        io.IRow CreateRow();

        io.IRowWriter CreateTable(string path);
        io.IRowReader ReadTable(string path);

        operations.IOperation RunMap (
            operations.MapOpConfig config,
            operations.IMapper mapper
        );

        operations.IOperation RunMapReduce(
            operations.MapReduceOpConfig config,
            operations.IMapper mapper,
            operations.IReducer reducer
        );
    }
}
